version: 2.1
jobs:
  validate:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: trussworks/circleci:62e7cada934784e47333e47175be728aa3475b02
    steps:
    - checkout
    - restore_cache:
        keys:
        - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
    - run:
        command: pre-commit run --all-files
        name: Run pre-commit
    - save_cache:
        key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
        paths:
        - ~/.cache/pre-commit
workflows:
  version: 2.1
  validate:
    jobs:
    - validate:
        context:
        - org-global
