name: validate

on: workflow_dispatch
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

jobs:
  validate:
    uses: trussworks/shared-actions/.github/workflows/validate.yml@main